name: Check Availability

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          install-dependencies: true
          install-chromedriver: true
      - run: pip install -r requirements.txt
      - run: python check_availability.py
        env:
          SECRET_DISCORD_WEBHOOK: ${{ secrets.SECRET_DISCORD_WEBHOOK }}
          CHROME_BINARY: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROMEDRIVER: ${{ steps.setup-chrome.outputs.chromedriver-path }}

